Amazon W1 PR
codesquad-members-2023/fe-max--shopping pull request #14
Opened 2023-04-03 09:16 UTC by lolWK

23.4.3(월) 이것저것 초기 설정중

---
- [ ] 상단 네비게이션
  - [ ] HTML,CSS
    - [ ] 상단바 검색바 사이즈
    - [ ] 본문 영역 사이즈 고정
  - [ ] 배송처 영역
    - [ ] 호버시 주소 변경 레이어 출현.
    - [ ] 각 호버 영역 벗어나면 모든 레이어 & 효과 사라짐
  - [ ] 로그인 영역
    - [ ] 메인 페이지 진입 1초 뒤 레이어(로그인 버튼) 출현 애니메이션. 로그인 영역에 호버하기 전까지 유지.
    - [ ] 호버시 레이어 확장, 배경 딤 처리
    - [ ] 각 호버 영역 벗어나면 모든 레이어 & 효과 사라짐
  - [ ] 검색바
    - [ ] placeholder 적용

- [ ] 히어로 영역 슬라이딩(Carousel)
  - [ ] HTML,CSS
  - [ ] 좌우 화살표 통해 내용 변경 기능
  - [ ] 화살표 누르지 않는 경우 10초마다 다음 내용으로 이동
  - [ ] 무한 슬라이딩으로 동작

2023-04-05 07:10 UTC, namse requested changes

2023-04-05 07:10 UTC, namse commented on src/js/hero.js
> +function fetchImages() {
프로미스 말고 async await 쭉 써보면 좋을듯

2023-04-05 07:10 UTC, namse commented on src/js/hero.js
> +    });
여기서 잡아버리면 의미가 있나요~? 여기서 잡아버리면, 위에 await하는 쪽은 문제가 없이 잘 데이터 온 줄 알고 코드를 진행할 것 같네요.

2023-04-06 05:55 UTC, altmit commented on src/js/hero.js
> +    }
left와 right 라는 조건은 둘중 하나만 적용되는것  같습니다. 
저는 이런 경우 if ... else if() 또는 삼항 연산자를 사용합니다.
위 두 방법과 if 문 2개를 쓰는 방법의 성능 차이는 거의 없다고 들었지만 if가 끝나고 아래로 내려와 새 if 문의 조건을 확인하는 불필요한 연산이 사라질 것 같아요!

2023-04-06 05:55 UTC, altmit commented on src/data/images.json
> +]
필요한 이미지 정보를 이렇게 미리 선언해 놓는 방법 너무 좋은것  같아요!

2023-04-06 05:55 UTC, altmit commented on src/js/hero.js
> +function fetchImages() {
남세께서도 말씀해 주신 내용이지만 제 생각도 한번 말씀드려봅니다!

지금은 이미지의 개수가 적기 때문에 문제가 없지만 이미지가 정말 많다면 모든 이미지를 가져오는 건 문제가 될 수 있다고 생각합니다.

우선 아직 구현하지 못했지만 제 생각으론 현재 이미지를 기준으로 index-2, index-1, index, index+1, index+2 번째로 총 5가지만 로드하여 화면에 준비합니다.
그리고 슬라이더가 움직일 때마다 현재 index가 바뀌니 그거에 맞는 이미지만 화면에 미리 준비하면 어떨까~ 생각해 봤습니다.

그리고 혹시 남세의 리뷰를 듣고 생각한 방법이 있다면 공유해주세요~

2023-04-06 05:55 UTC, altmit commented on src/js/hero.js
> +      }
위 else if와 비슷하게 해결 가능할 것 같습니다.
그리고 `slide.style.transition = 'none';` , `moveSlides();`
두 코드가 중복으로 사용 되고 있습니다.

위 두 코드를 밖으로 빼는 방법도 있을 것 같네요~

2023-04-07 07:46 UTC, closed without merging