[Kakamotobi] Amazon Week2
codesquad-members-2023/fe-max--shopping pull request #46
Opened 2023-04-14 09:00 UTC by Kakamotobi

2023-04-15 09:40 UTC, junzero741 requested changes
안녕하세요 Kakamotobi!
비록 화상이었지만 얼굴보고 인사를 한 뒤에 리뷰를 하니 아무래도 좀 더 친근한 느낌이 드는 것 같습니다. ㅎㅎ
전체적으로 코드가 일관성이 있어서 리뷰하기에 어려움이 없어서 좋았습니다.
저번에 면담했을 때 아키텍처에 대해서 고민을 하고 계시다니 관련 질문을 좀 드리자면,

1. 폴더명을 나누는 기준?
components 폴더와 common 폴더를 나누는 기준이 조금 모호한 것 같습니다.
제가 봤을 땐 components 폴더도 충분히 common 해보이거든요.
둘을 나누는 기준이 무엇인지 궁금합니다!

2. 컴포넌트의 재사용성
이건 코드에도 코멘트를 남겨놨고, 질문이라기보단 피드백에 가까운 것 같은데요,
요즘 제가 중요하게 생각하는 부분이라 한 번 더 강조를 하고 싶어서 추가 코멘트를 좀 남기자면,
각 컴포넌트의 역할은 개발자가 컴포넌트의 이름을 읽었을 때 90%이상 예상할 수 있어야 한다고 생각해요.
그렇지 않으면 서비스의 규모가 커졌을 때 내가 원하는 기능을 파일 이름만 보고도 찾아낼 수 있거든요.

반대로,
서버를 직접 구현하신 점이나, shadowDOM 등의 새로운 시도를 하신 점, 매직넘버를 최소화 하신 점 등은 좋아보입니다. 무엇보다, 앞에서도 언급했지만 전체적으로 코드 일관성이 좋아서 코드를 읽기 편했던 점도 아주 좋았습니다! ㅎㅎ

우선은 사전에 합의한 대로, change request 상태로 두겠습니다. 
추가로 수정할 용의가 있든, 다음 주차에 추가로 진행할 예정이든 주말 내에만 코멘트 또는 DM으로 알려주시면 머지해드리겠습니다. ㅎㅎ 이번 주도 고생 많으셨습니다 🥳

2023-04-15 09:40 UTC, junzero741 commented on src/utils/index.js
> +};
kakamotobi 는 만약 유틸 함수가 많아진다면 유틸 함수들을 어디에서 관리하실 생각이신가요??

2023-04-15 09:40 UTC, junzero741 commented on src/styles/index.scss
> +
root 라는 이름만 봐서는 프로젝트의 최상위 엘리먼트를 가리키는 것 같은데, 맞을까요?
만약 그렇다면 scroll-behavior: smooth 가 default 로 적용된 이유가 궁금합니다.

2023-04-15 09:40 UTC, junzero741 commented on src/styles/config/_component-reset.scss
> +  color: $color-white;
모든 a 태그가 white 색상이라고 단언하는 것은 조금 위험해 보입니다.
하얀색 a 태그를 위한 클래스를 따로 두는 것이 유지보수에 용이할 것 같습니다.

2023-04-15 09:40 UTC, junzero741 commented on src/styles/components/common/ToolTip.scss
> -  // }
사용하지 않는 주석 혹은 코드를 소스코드에서 바로바로 지우는 건 좋은 습관인 것 같습니다. 👍

2023-04-15 09:40 UTC, junzero741 commented on src/styles/components/TopHeader.scss
> +  height: 1805px;
1805 px 값이 의미하는게 무엇인지 궁금합니다!

2023-04-15 09:40 UTC, junzero741 commented on src/styles/components/TopHeader.scss
> +  z-index: 2;
z-index 가 엘리먼트의 z 좌표 우선순위를 다루는 값이란 걸 아신다면,
이렇게 매직넘버로 z-index 를 관리했을 때의 위험성에 대해서 상상해보시는 것도 좋을 것 같아요.

2023-04-15 09:40 UTC, junzero741 commented on src/styles/components/SearchForm.scss
> +}
input 이나 button 같은 기본 엘리먼트의 스타일에 width, height 값을 고정으로 넣고 계신데요.
이렇게 하면 동료나 미래의 자신이 button 태그나 input 태그를 사용할 때 이쪽 코드의 존재를 알아차리기 어렵다는 단점이 있습니다.
이 파일이 SearchForm 이라는 컴포넌트만의 스타일만을 담당한다고 하더라도요.
SearchForm 의 어떤 역할을 하는 버튼인지를 클래스명에 명시하고, 해당 클래스에 스타일을 주는 게
유지보수에 용이할 것 같아요.

2023-04-15 09:40 UTC, junzero741 commented on src/styles/components/AutocompletePanel.scss
> +@use "../config/design-system.scss" as *;
공통 디자인 시스템을 끌어와서 사용하는 패턴은 동료간 협업, 분업에 좋을 것 같네요 👍

2023-04-15 09:40 UTC, junzero741 commented on src/pages/MainPage.js
> +    <infinite-carousel></infinite-carousel>
지금 상황에서는 조금 오버스펙일 수 있지만,
무한 캐로셀은 아마존 홈페이지라는 도메인과는 완전히 무관한 컴포넌트로 존재하는 게 역할의 분리 측면에서 좋을 것 같아요.
캐로셀 컴포넌트를 사용하는 아마존 홈페이지 도메인에 특화된 캐로셀을 만들고, MainPage 에서 사용해보는 건 어떨까요?
Compound Compoent 라는 키워드로 찾아보시면 도움이 될 것 같습니다.

2023-04-15 09:40 UTC, junzero741 commented on src/components/common/ToolTip.js
> +    this.shadowRoot.host.getRootNode().host.dispatchEvent(dimEvt);
꼭 그렇게 구현해야 한다는 것은 아니지만, 
보통 툴팁, 모달 등은 자신이 dimmed 되는 영역 자체를 소유하고, dimmed 여부를 컨트롤 하는 경우가 많습니다.
지금처럼 툴팁이 상위의 엘리먼트가 누구던 간에 dimmed 되도록 명령하는 형태가 아니라요.

2023-04-15 09:40 UTC, junzero741 commented on src/components/TopHeader.js
> +        <search-form></search-form>
children 이 들어갈 여지가 있는 컴포넌트일까요? 그렇지 않다면 self-closing tag 를 사용하는 방법도 고려해보시면 좋을 것 같습니다.

2023-04-15 09:40 UTC, junzero741 commented on src/components/SearchForm.js
> +  }
SearchForm 컴포넌트의 역할은 어디까지일까요?
이 컴포넌트를 그대로 가져다가 아마존 서비스의 다른 검색창에 사용할 수 있을까요?
그게 가능하게 하려면 SearchForm 의 역할을 어디까지 제한할 지 고민해보시면 좋을 것 같습니다.
'UI 로직과 비즈니스 로직의 분리' 라는 키워드로 공부해보세요!

2023-04-15 09:40 UTC, junzero741 commented on src/components/SearchForm.js
> +    shadowRoot.append(template.content.cloneNode(true));
이 코드가 컴포넌트들의 생성자 함수 내에서 중복되고 있는 것으로 보이는데요.
중복을 제거할 방법에 대해서 고민해보시면 좋을 것 같습니다.

2023-04-15 09:40 UTC, junzero741 commented on src/components/SearchForm.js
> +`;
html 파일을 작성할 때와 달리, 문자열로 ui 를 코딩하면서 불편한 점은 없으셨나요?

2023-04-15 09:40 UTC, junzero741 commented on src/components/InfiniteCarousel.js
> +  }
InfiniteCarousel 이 히어로 이미지들을 불러오는 데에만 국한된 컴포넌트가 되어가고 있는 걸로 보입니다.
다른 페이지에도 InifniteCarousel 을 사용할 수 있게 하려면 어떻게 수정해야 할까요?

2023-04-15 09:40 UTC, junzero741 commented on src/components/InfiniteCarousel.js
> +  <ul class="slides-container"></ul>
시멘틱 태그로 바꾸신 걸까요? 좋습니다 👍

2023-04-15 14:03 UTC, Kakamotobi commented on src/utils/index.js
> +};
그 부분은 어떤 유틸 함수들이 추가가 되느냐에 따라서 달라질것 같습니다. 아직 유틸 함수가 `debounce` 하나밖에 없어서 미리 구조를 정해버리는 것 보다 필요에 따라 적절하게 관리하는게 낫다고 판단했습니다.

2023-04-15 14:03 UTC, Kakamotobi commented on src/styles/index.scss
> +
네, `:root` selector는 `html` selector와 동일하지만 specificity가 더 높은 걸로 알고 있습니다.
MainFooter에 있는 back to top 링크를 누르면 `smooth`하게 scroll이 되기 위함입니다.

2023-04-15 14:04 UTC, Kakamotobi commented on src/styles/config/_component-reset.scss
> +  color: $color-white;
이 부분은 수정하는 것을 깜빡했습니다 👍

2023-04-15 14:04 UTC, Kakamotobi commented on src/styles/components/TopHeader.scss
> +  height: 1805px;
이 부분은 `.dimmed-layer`의 `height`를 top header를 제외한 전체 페이지의 `height`로 설정하는데 실패해서 임의로 설정해 둔 값입니다.😅

2023-04-15 14:05 UTC, Kakamotobi commented on src/styles/components/TopHeader.scss
> +  z-index: 2;
나중에 z-index를 부여할 때 계속해서 랜덤하게 높은 매직넘버를 쓰게 되는 상황 등이 생길 것 같네요.
이렇게 하는 것보다 차라리 SCSS/CSS variables을 쓰면 그나마 유지보수하기 더 편할것 같습니다.

2023-04-15 14:06 UTC, Kakamotobi commented on src/styles/components/SearchForm.scss
> +}
저도 동의하는 부분입니다. 특히, 컴포넌트가 클 수록 그럴거라고 생각합니다.
하지만 지금은 저 혼자 개발중이고 버튼이 하나고 하는 역할이 self-explanatory한 것 같아 굳이 미리 클래스명을 주지 않아도 될것 같다고 생각했습니다. 후에 버튼을 추가하게 되면 그때 해도 크게 어렵지 않을거라고 생각했습니다.

2023-04-15 14:07 UTC, Kakamotobi commented on src/pages/MainPage.js
> +    <infinite-carousel></infinite-carousel>
추천 감사합니다 👍

2023-04-15 14:07 UTC, Kakamotobi commented on src/components/common/ToolTip.js
> +    this.shadowRoot.host.getRootNode().host.dispatchEvent(dimEvt);
요구사항에는 dim되는 영역이 늘 같은 곳이라 tooltip, 등 dim이 필요한 모든 요소들이 각각 하나씩 dimmed되는 영역을 가지는 것보다 하나의 dim영역을 두고 각 요소들이 필요에 따라 dim 요청을 보내는게 더 효율적일거라고 생각했습니다. 그리고 dim을 하는 tooltip을 왔다갔다 하면서 dim layer가 중첩이 되는 것을 피하고 싶었습니다.

Dim layer를 가장 중립적인 최상단에 두고 싶었지만 Shadow DOM의 특성상 외부 요소에 대한 접근이 쉽지 않아서, 그리 좋은 방법은 아닌것 같지만, 일단 가장 근접한 부모 컴포넌트에 두게 되었습니다.

2023-04-15 14:08 UTC, Kakamotobi commented on src/components/TopHeader.js
> +        <search-form></search-form>
저도 아쉽지만 custom element는 self-closing할 수 없고 opening과 closing tag로 이루어져야 한다고 합니다. 👍

2023-04-15 14:09 UTC, Kakamotobi commented on src/components/SearchForm.js
> +  }
지적 감사합니다 👍

2023-04-15 14:10 UTC, Kakamotobi commented on src/components/SearchForm.js
> +`;
Format이 안되고 theme이 적용이 안되서 불편했으나 "string-highlight"라는 VSCode extension을 이용해서 자동 format은 안되지만 가독성은 개선되었습니다.

2023-04-15 14:10 UTC, Kakamotobi commented on src/components/InfiniteCarousel.js
> +  }
Carousel에 쓰일 data를 InfiniteCarousel이 아닌 InfiniteCarousel의 사용처(부모 컴포넌트)에서 fetch를 하고 데이터만을 건내주는 방식으로 하면 재사용이 가능할 것 같네요.

2023-04-15 14:24 UTC, Kakamotobi commented
지적하신 바와 같이 폴더명을 나눈 기준이 모호하네요. common폴더에는 여기저기서 사용될 기본 UI 요소(Ex: button, tooltip)를 뜻했던건데 CardItem이 들어가 있어서 모호해진거 같네요. CardItem 컴포넌트를 components 폴더로 빼면 좀 더 명확할 것 같습니다.

지적 감사합니다. 🙏

2023-04-16 04:47 UTC, junzero741 commented on src/styles/index.scss
> +
그렇다면 동료와 함께 개발할 땐 smooth 를 root 가 아닌 footer 의 back to top 을 눌렀을 때로 제한을 두는 게 좋을 것 같아요.
브라우저의 스크롤 애니메이션 기본 스펙이 변경된 프로젝트라고 예측하기가 어려울 수 있거든요.

2023-04-16 04:55 UTC, junzero741 approved these changes
중복 코드도 제거되고, 폴더 구조도 조금 더 깔끔해졌네요.
좋습니다 ㅎㅎ

2023-04-16 04:55 UTC, junzero741 commented on src/pages/MainPage.js
> +    return await res.json();
👍

2023-04-16 04:55 UTC, junzero741 commented on src/components/SearchForm.js
> +    super(template);
Component 클래스를 만들어서 중복 코드를 제거했네요. 아주 좋습니다 👍

2023-04-16 04:56 UTC, junzero741 commented
추가로 작업하실게 있다면 오늘중으로 알려주세요 👍

2023-04-16 06:05 UTC, Kakamotobi commented on src/styles/index.scss
> +
`scroll-behavior: smooth`는 scrolling box에 한해서 적용이 되는 걸로 알고 있습니다.
제 상황에서는 페이지의 밑에서 페이지의 위로 가기 때문에 상단 요소인 `html`이 scrolling box가 되서 `html` (또는 `:root`)에 `scroll-behavior`를 적용해야되는 것 같습니다.👍

2023-04-16 06:08 UTC, Kakamotobi commented
더 고치고 싶지만 오늘 작업을 하지 못할것 같아서 merge해주시면 감사하겠습니다.
리뷰 감사합니다 🙏

2023-04-16 23:07 UTC, merged