[Jello] 아마존 쇼핑몰 Week2 PR#2
codesquad-members-2023/fe-max--shopping pull request #52
Opened 2023-04-14 10:34 UTC by hjsong333

안녕하세요 Goody!
앞으로 3주간 신세지게 될 Jello입니다. 😄

이번주는 지난주에 이어서 Amazon 사이트 검색창을 만드는 미션이었습니다.
사실, 수요일까지 이전 코드를 좀더 보기 좋게 나누고 정리하는데 써버려서 검색창의 기능을 끝까지 구현하지는 못했어요.
이틀간 클래스를 적용해보기에도 시간이 부족해서 객체지향은 가까이 가보지도 못했습니다. 😭 

이번 미션을 진행하면서 고민했던 부분은 '**클래스를 몇개나 만들어야 할까**' , '**클래스의 역할은 어디까지여야 할까**'였습니다.
- 내용이 변하지 않는 부분은 미리 HTML로 만들어두고 시작했습니다.
- 검색창/검색 레이어/검색 목록으로 크게 3개의 클래스를 만들어 기능 구현했습니다.
- 검색 목록의 경우에는 목록을 채울 데이터를 불러와서 DOM 요소를 만드는 기능을 SuggestionListBuilder 클래스를 상속받은 클래스들에게 요청합니다. (HistoryListBuilder, RecommendListBuilder) 여기서 각 Builder 클래스들은 종류에 맞는 DataFetcher를 생성해서 데이터를 요청합니다.(HistoryFetcher, RecommendFetcher)

<details>
<summary>설명이 조잡해서 이해 안 되실까봐 구조도를 그려봤습니다</summary>

![클래스 구조](https://user-images.githubusercontent.com/60080167/232018863-93c99876-5ce0-4e0e-86ca-44c06bd2e480.png)
</details>

기능 구현을 하면서도 오히려 흐름을 따라가기 불편해져서 잘못 사용하고 있다는 느낌이 듭니다. 
위의 2가지에 유의해서 리뷰를 해주시면 클래스를 사용하고 설계를 하는데 도움이 될 것 같습니다.

부족한 실력이지만 잘 부탁드리겠습니다. 🙏 

## 주요 기능 및 요구사항

### 📌 **검색창**
- [x] 검색바를 클릭하면 추천 검색어 10개가 표시된 레이어를 화면에 렌더링한다.
- [x] 검색한 내역을 최대 5개까지 추천 검색어 레이어에 표시하고 그 아래로 추천 검색어를 10개 표시한다.
- [x] 추천 검색어 레이어와 동시에 딤처리 영역을 렌더링한다.
- [x] 키보드의 화살표 키로 검색 내역과 추천 검색어를 이동하면 배경색을 변경한다.
- [ ] 검색한 키워드를 저장하고 최근 검색 목록에 표시한다.
- [ ] X아이콘을 누르면 최근 검색 목록을 제거한다.
- [ ] 검색어를 입력하면 연관 검색어를 10개까지 표시한다.

## 미리보기 및 프로젝트 실행 방법

### 🎦 미리보기
<details>
<summary>미리보기 영상</summary>

https://user-images.githubusercontent.com/60080167/232010120-57c1479e-227d-459a-abcf-0c7c0c27efd1.mp4
</details>

### 🚀 프로젝트 실행 방법
1. [**git repository**](https://github.com/hjsong333/fe-max--shopping.git)를 클론받습니다.
4. `develop` 브랜치로 이동합니다.
5. 터미널에서 `npm start` 명령어를 입력합니다.
6. 실시간으로 제가 만든 페이지를 보실 수 있습니다!

2023-04-15 10:24 UTC, junzero741 requested changes
안녕하세요 Jello!
직접은 아니지만 화상으로 얼굴 뵙고 나서 리뷰하게 되니 뭔가 친근한 느낌이 들고 좋네요. ㅎㅎㅎ
면담 때 걱정하셨던 것과 달리 코드가 전체적으로 깔끔하고 역할도 나쁘지 않게 나뉘어져 있는 것 같아요.
특히 데이터 fetch 를 담당하는 부분과 화면 렌더링 UI 를 분리하려 노력하신 부분이 인상적이었습니다.
전체적인 폴더 구조도 역할에 맡게 잘 나뉘어져 있는 것 같구요.

다만, 당장 신경쓰실 부분은 아니긴 하나
src 폴더 내에 public 한 asset 들이 위치하고 있는 것은 조금 아쉬운 것 같아요.
프로젝트에서 public 한 영역과 private 한 영역을 어떻게 나눌 지 고민해보셨으면 좋겠습니다.

이외의 자세한 피드백은 코드에 코멘트 남겨드렸으니 참고해주세요!
이번 주도 고생 많으셨습니다 🥳

ps 코드 머지는 사전에 협의한대로 Jello 가 코멘트, 혹은 DM 으로 말씀해주시면 그때 하도록 하겠습니다! 피드백이 있으니 change request 를 드리지만, 꼭 수정하셔야 하는 것은 아니니 머지 원할 때 편하게 알려주세요 😆

2023-04-15 10:24 UTC, junzero741 commented on src/style/scss/style.scss
> +  height: 100vh;
dimmed 영역을 현재 사용자의 눈에 보이는 화면 높이로 잡으면,
만약 dimmed 되는 영역의 페이지가 스크롤되는 페이지면 어떻게 될까요?

2023-04-15 10:24 UTC, junzero741 commented on src/style/scss/style.scss
> +  // top: 180%;
사용되지 않는 코드로 보이는데요, 삭제하지 않고 주석처리한 이유가 있을까요?

2023-04-15 10:24 UTC, junzero741 commented on src/style/scss/style.scss
> +    z-index: 10;
만약 z-index 를 사용하는 엘리먼트가 1000개가 된다고 상상해보면요,
어느 엘리먼트가 더 상위에 와야 하는지 정할 때 몹시 난감할 수 있지 않을까요? 
이런 상황을 어떻게 방지할 수 있을지 고민해보시면 좋을 것 같아요.

2023-04-15 10:24 UTC, junzero741 commented on src/style/scss/_values.scss
> +  src: url("/src/asset/fonts/Pretendard-Medium.woff") format('woff');
ttf 와 woff 폰트파일의 차이점은 무엇인가요? 바꾸게 된 이유도 궁금합니다.

2023-04-15 10:24 UTC, junzero741 commented on src/js/utils/domUtils.js
> +export const removeHiddenClass = (element) => element.classList.remove('hidden');
함수의 이름이 단순히 함수 내부를 설명하는 데에 그치고 있는 것 같아요.
그래서 hidden 클래스를 제거하면 어떤 일이 일어날지 추리(?) 를 해야 하는 불편함이 있습니다.
이 함수가 hidden 클래스를 제거함으로써 '이루고자 하는 일'이 무엇인가요?
'이루고자 하는 일' 을 함수의 이름으로 짓는다면 동료가 함수의 역할을 추리하지 않아도 되어서 편리할 것 같아요.

2023-04-15 10:24 UTC, junzero741 commented on src/js/utils/dataFetcher.js
> +}
데이터를 불러오는 비즈니스 로직을 UI 와 분리해놓은 건 아주 좋은 것 같습니다. 👍
다만, HistoryFetcher 와 RecommendFetcher 는 무엇에 대한 history 혹은 Recommend 인지 조금 헷갈릴 소지가 있어보입니다.
모든 dataFetcher를 이 파일 하나에 몰아넣는 것도 모듈의 역할이 너무 커지는 것 같구요.

2023-04-15 10:24 UTC, junzero741 commented on src/js/index.js
> +  const url = 'http://localhost:3000/'
무슨 역할을 하는 코드일까요?

2023-04-15 10:24 UTC, junzero741 commented on src/js/components/searchBar/SuggestionListBuilder.js
> +const API_URL = 'http://localhost:3000/';
조금 더 어울리는 위치가 있을 것 같아요.
글로벌하게 사용되는 값이니까요!

2023-04-15 10:24 UTC, junzero741 commented on src/js/components/searchBar/SearchSuggestion.js
> +    console.log('above')
테스트용 코드인 것 같은데요. 소스코드에는 포함되지 않는게 좋을 것 같습니다!

2023-04-15 10:24 UTC, junzero741 commented on src/js/components/searchBar/SuggestionListBuilder.js
> +  }
이 클래스는 UI 를 담당하는 클래스인가요? 아니면 데이터를 담당하는 클래스인가요?

2023-04-15 10:24 UTC, junzero741 commented on src/js/components/searchBar/SearchLayer.js
> +    closeAllLayers();
모달같이 글로벌한 영역에 영향을 끼치는 UI 의 경우, 모달을 닫는 함수의 실행을 모달이 아닌 다른 개체가 담당하게 하면,
지금처럼 모달이 닫혀야 하는 모든 부분에 대해서 closeAllLayers() 를 넣어야 하는 일이 생깁니다.
당장은 서비스에 기능이 많지 않으니 이게 크게 다가오지 않을 수 있으나,
jello 가 만든 UI 가 1000개라고 생각해보면, 이게 얼마나 귀찮은지 체감할 수 있을 것 같아요.
따라서 모달이 열리고 닫히는건 모달이 알아서 하게 처리해보면 좋을 것 같아요!

2023-04-15 10:24 UTC, junzero741 commented on src/js/components/hero.js
> +  }, 50);
50이라는 숫자가 의미하는게 뭘까요??

2023-04-15 10:24 UTC, junzero741 commented on index.html
> +            <img src="/src/asset/img/hero_2.jpg" alt="2번째 히어로 이미지" />
img 태그의 alt 가 의미하는게 무엇인지 공부해보시면 좋을 것 같습니다!

2023-04-15 10:24 UTC, junzero741 commented on .gitignore
> +/src/style/css/*.css.map
css 파일과 css.map 파일의 차이점은 무엇인가요?

2023-04-15 12:29 UTC, hjsong333 commented on src/style/scss/style.scss
> +  height: 100vh;
dimmed 영역은 시작 지점을 쉽게 잡기 위해서 네비게이션의 자식 요소로 넣어놨습니다.
그 때문에 페이지 전체의 높이를 css 만으로 잡기 힘들어 일단 100vh로 급하게 처리해놓은 부분이네요.

고민해봤지만 CSS로 처리하는게 쉽지 않아 자바스크립트로 높이를 계산해서 초기화해주는 방식으로 개선해봤습니다.

```
function initDimmedLayerStyle() {
  const dimmedLayer = $('.dimmed-layer');
  const bodyHeight = $('body').offsetHeight;
  const navBarHeight = $('.nav-bar').offsetHeight;

  dimmedLayer.style.height = `${bodyHeight - navBarHeight}px`;
  dimmedLayer.style.minHeight = `calc(100vh - ${navBarHeight}px)`;
}
```

2023-04-15 12:32 UTC, hjsong333 commented on src/style/scss/style.scss
> +  // top: 180%;
지우는 걸 깜빡했네요 😅 
커밋 전에 점검하도록 노력하겠습니다.

2023-04-15 12:38 UTC, hjsong333 commented on src/js/index.js
> +  const url = 'http://localhost:3000/'
이전에 사용하던 코드인데 지우는걸 잊었습니다. 😓 
원래는 dataFetcher 객체를 여기서 생성해서 드릴링으로 searchSuggestion까지 전달하게 되어있었습니다.

2023-04-15 12:39 UTC, hjsong333 commented on src/js/components/searchBar/SearchSuggestion.js
> +    console.log('above')
필요없는 코드가 많이 남아있네요 💦
console.log 와 주석 일괄 제거했습니다.

2023-04-15 12:41 UTC, hjsong333 commented on src/js/components/searchBar/SuggestionListBuilder.js
> +  }
초기 설계는 UI를 담당하는 클래스였지만, 데이터를 불러오는 기능과 강한 연관성이 있어서 의도적으로 결합시켜봤어요!

2023-04-15 12:55 UTC, hjsong333 commented on src/js/components/hero.js
> +  }, 50);
다음 이미지를 준비할 때까지 대기시간입니다.
대기시간을 주지 않았을 때, 스타일 변경이 너무 빠르게 일어나서 애니메이션이 반대로 동작하기도 했습니다.

2023-04-15 13:12 UTC, hjsong333 commented on index.html
> +            <img src="/src/asset/img/hero_2.jpg" alt="2번째 히어로 이미지" />
Goody의 코멘트를 보고 반성합니다.
alt의 역할과 적합한 값이 무엇일지 고민하지 않았던 것 같습니다 😞

alt는 이미지에 대한 대체 테스트(Alternative text)를 지정하는데 사용되는데 사용되는 속성입니다.
이 속성은 사용자가 이미지를 볼 수 없는 경우나 이미지가 로드되지 않았을 때 **이미지에 대한 정보를 전달**할 수 있어야 합니다.
즉, alt 값만 보더라도 이미지의 내용을 알 수 있어야합니다.

"2번째 히어로 이미지"로는 해당 이미지의 내용을 전혀 유추할 수 없으니 부적절한 값이라고 생각합니다.

2023-04-15 13:13 UTC, hjsong333 commented on index.html
> +            <img src="/src/asset/img/hero_2.jpg" alt="2번째 히어로 이미지" />
여담으로 이미지가 배경으로 사용되는 경우에는 alt를 비워두거나 CSS의 background-image를 사용하는게 좋다는 걸 알게 됐습니다.

2023-04-15 13:37 UTC, hjsong333 commented on .gitignore
> +/src/style/css/*.css.map
css 파일은 웹 페이지 스타일을 정의합니다.
css.map 파일은 css 파일의 어떤 속성이 어떤 파일의 어느 위치에서 왔는지 매핑 정보를 정의합니다.

2023-04-15 14:12 UTC, hjsong333 commented on src/style/scss/style.scss
> +    z-index: 10;
z-index를 1000개나 관리해야 한다면 끔찍하네요.
그렇지만 모든 UI가 다른 z-index를 가지는 건 아니라고 생각되네요.
그래서 몇 종류의 사용할 z-index를 정의해놓고 UI별로 값을 불러와서 사용하면 관리에 용이하다고 생각합니다.
Sass의 경우에는 변수화 해놓고 쓸 수 있겠네요.

비슷하게, z-index를 관리하기 위한 모듈을 두고 컴포넌트별 z-index를 정의한 뒤 export 해주는 방식도 가능하지 않을까 생각됩니다.

2023-04-15 15:45 UTC, hjsong333 commented on src/style/scss/_values.scss
> +  src: url("/src/asset/fonts/Pretendard-Medium.woff") format('woff');
woff는  **압축된 포맷이기 때문에 로드가 더 빠르다**고 알고 있습니다.
또, 웹 페이지의 폰트를 위해서 만들어져서 대부분의 메이저 브라우저에서 지원합니다.
오래된 브라우저를 지원하기보다는 로드 성능이 좋은편이 사용자 경험에 좋을 것이라 생각해서 교체했습니다.

2023-04-15 16:26 UTC, hjsong333 commented on src/js/utils/domUtils.js
> +export const removeHiddenClass = (element) => element.classList.remove('hidden');
함수 이름을 지을 때 2가지 기준 사이에서 고민을 많이 하는데요,
1. 함수 내부에서 어떤 일을 하는지
2. 함수가 최종적으로 어떤 역할을 하는지
Goody의 말을 듣고 관점을 바꿔보니 2번 기준이 더 좋을 것 같습니다! 👍

2023-04-15 16:39 UTC, hjsong333 commented on src/js/utils/domUtils.js
> +export const removeHiddenClass = (element) => element.classList.remove('hidden');
domUtils.js의 함수 이름을 이렇게 바꿔봤는데 어떨까요?
- removeHiddenClass -> showHiddenElement
- addHiddenClassIfAbsent -> hideElement
- removeOverClass -> removeHighlightFromElement
- addOverClassIfAbsent -> highlightElement

2023-04-15 16:41 UTC, hjsong333 commented on src/js/components/searchBar/SuggestionListBuilder.js
> +const API_URL = 'http://localhost:3000/';
constants.js 파일을 만들어 상수들을 모아서 관리해볼까요?

2023-04-15 16:47 UTC, hjsong333 commented on src/js/utils/dataFetcher.js
> +}
일단 조금 더 명확한 이름으로 변경해보겠습니다.
그리고 dataFetcher들의 차이점이 많지 않고 코드가 길지 않아서 한 파일로 뭉쳐는데, 역시 파일을 다 나누는게 좋을까요?

2023-04-15 16:48 UTC, hjsong333 commented on src/js/utils/dataFetcher.js
> +}
클래스별 기능 차이가 크지 않아 DataFetcher 하나만 두고 getData에서 매개변수로 파라미터를 받는 방식으로 변경할까 고민중인데 어떤가요?

2023-04-16 04:30 UTC, hjsong333 commented on src/js/components/searchBar/SearchLayer.js
> +    closeAllLayers();
확실히 번거로운 일이네요. 
고민한 결과, layer 클래스를 가진 요소들을 열때 아래의 함수를 사용하도록 변경했습니다.
```
export const openLayer = (...elements) => {
  closeAllLayers();
  openDimmedLayer();
  elements.forEach((element) => showHiddenElement(element));
}
```

2023-04-16 05:00 UTC, junzero741 commented on src/style/scss/style.scss
> +  height: 100vh;
자바스크립트로 스타일을 설정해주셨군요! 물론 이 방법도 문제를 해결했다는 측면에서는 나쁘지 않지만,
HTML, CSS 만으로도 해결하는 방법이 있는데, dimmed 되는 영역을 body 태그의 바로 아래 자식으로 두면,
dimmed 의 높이를 body의 높이에 대해 height: 100% 로 설정하면 굳이 dimmed 영역의 높이를 프로그래밍적으로 계산하지 않아도 
자동으로 정해줄 수 있지 않을까요??

2023-04-16 05:02 UTC, junzero741 commented on src/style/scss/style.scss
> +    z-index: 10;
말씀해주신대로 공통으로 스타일을 관리하는 곳에 변수화 해놓고 사용하면 유지보수가 쉽겠죠! 금방 눈치채셨군요 👍
base 를 정해놓는다는 접근도 신선하고 좋습니다.

2023-04-16 05:03 UTC, junzero741 commented on src/js/utils/domUtils.js
> +export const removeHiddenClass = (element) => element.classList.remove('hidden');
좋네요. 이름만 봐도 어떤 일을 하는 함수인지 분명하게 나타나는 것 같아요. 
동료 개발자는 이제 이 함수의 내부에서 어떤 일을 하는지 신경쓰지 않고, 이름만 보고도 함수를 편하게 가져다 쓸 수 있다는 측면에서
협업과 시간 절약에 유리해진 코드가 된 것 같습니다.

2023-04-16 05:05 UTC, junzero741 commented on src/js/utils/dataFetcher.js
> +}
데이터를 불러오는 소스가 다르다면 각 dataFetcher를 각자의 파일들로 나눠놓는게 유지 보수에 좀 더 용이할 것 같아요.
추천 목록 기능에 버그가 생겼을 때 추천 목록을 불러오는 코드를 한 파일의 한 클래스만 훑어보면 되기 때문입니다.

2023-04-16 05:06 UTC, junzero741 commented on src/js/utils/dataFetcher.js
> +}
두번째 방법도 나쁘지 않네요. 물론 정답은 없으니, 최대한 코드 중복을 제거하고 각자의 역할과 관심사가 섞이지 않게 유의하시면서 진행하시면 좋을 것 같습니다. 👍

2023-04-16 05:07 UTC, junzero741 commented on src/js/components/searchBar/SuggestionListBuilder.js
> +const API_URL = 'http://localhost:3000/';
상수들을 모아서 관리하는 것도 좋고, API_URL 이라는 상수의 목적을 생각해서, 해당 상수를 관리해야 할 주체가 누구인지 고민해보시고 위치를 옮기는 것도 좋습니다.

2023-04-16 05:10 UTC, junzero741 commented on index.html
> +            <img src="/src/asset/img/hero_2.jpg" alt="2번째 히어로 이미지" />
좋네요. ㅎㅎㅎ 저도 잘 되지 않아서 자주 반성하는 부분 중 하나인데,
당연하게 쓰고 있던 기능들의 원래 용도를 분명하게 알고 쓰는 것이 중요한 것 같아요.

2023-04-16 05:12 UTC, junzero741 approved these changes
피드백 반영해서 수정하신 부분들 잘 봤습니다. ㅎㅎ
점점 코드가 깔끔해지고 있는 것 같아서 좋네요.

approve 해둘테니, 추가 수정사항 있으시면 주말중에 커밋이나 코멘트 남겨주세요! 👍 
월요일 이전에 머지하도록 하겠습니다.

2023-04-16 05:30 UTC, hjsong333 commented on src/style/scss/style.scss
> +  height: 100vh;
그렇군요! 
말씀하신 방법도 시도 해봤는데, 현재 body 태그 안의 내용이 없어서 굉장히 짧아지길래 포기했었습니다.
하지만 min-height으로 최소 길이를 설정해주면 HTML, CSS만으로도 가능하겠네요! 
조언 감사합니다! 🙇

2023-04-16 05:40 UTC, hjsong333 commented on src/js/components/searchBar/SuggestionListBuilder.js
> +const API_URL = 'http://localhost:3000/';
데이터를 가져오거나 저장할 때 사용하는 상수라서 DataFetcher에 둘까도 생각해봤지만, 범용적으로 사용될 수 있는 클래스라 포기했습니다.

2023-04-16 06:22 UTC, hjsong333 commented
답변을 달면서 말씀드렸던 부분들 수정해서 커밋했습니다. 
이제 머지해주시면 될 것 같습니다. 🙏 

Goody의 피드백을 받으면서 코드의 의미와 역할이 명확해지는게 느껴져서 너무 좋아요! 😂
그러면서 한편으로는 더 신중하게 코드를 작성해야겠다는 생각도 들었습니다.
이번 주 리뷰 고생 많으셨고 앞으로 2주간도 잘 부탁드리겠습니다. 🎉

2023-04-16 23:06 UTC, merged