[박하] 아마존 1주차 PR #1
codesquad-members-2023/fe-max--shopping pull request #9
Opened 2023-04-03 07:31 UTC by bakhacode

코드 작성 이전에 어떤 방식으로 진행할지 정리와 설계를 확실하게 해놓기로 목표했다.

[ ] 브레인 스토밍한 키워드들 학습
[ ] 개발계획에 맞춰서 빠른 구현 진행

2023-04-05 07:04 UTC, namse requested changes

2023-04-05 07:04 UTC, namse commented on src/components/modal.js
> +    hideAddressModal();
이름만 봐서는 껐다 켰다 하는 코드로 보이는데, 실제론 아니다. 이름을 좀 명확하게 해얗나다.

2023-04-05 07:04 UTC, namse commented on src/components/modal.js
> +export function modal() {
이 이름도 쵸큼 그런 느낌이

2023-04-06 04:14 UTC, bakhacode commented on src/components/modal.js
> +    hideAddressModal();
```js
function initModal() {
    showLoginModalOnLoad();
    attachLoginEventListeners();
    attachAddressEventListeners();
}
```

```js
export function showLoginModalOnLoad() {
    document.addEventListener(
        "DOMContentLoaded",
        fadeInModal(".login-modal", 1000)
    );
}

export function fadeInModal(modalClassName, time) {
    const modal = document.querySelector(modalClassName);
    setTimeout(() => {
        modal.classList.add("show");
    }, time);
}

export function hideModal(modalClassName) {
    const modal = document.querySelector(modalClassName);
    modal.classList.remove("show");
}

export function addDimming(className) {
    const elem = document.querySelector(className);
    elem.classList.add("dim");
}
export function removeDimming(className) {
    const elem = document.querySelector(className);
    elem.classList.remove("dim");
}
```

스근하게 나눠줬습니다 😎

2023-04-06 04:17 UTC, bakhacode commented on src/components/modal.js
> +export function modal() {
함수들을 모아모아 initModal로 변경! setupModal이 나으려나요

2023-04-06 05:57 UTC, qkdflrgs commented on src/styles/scss/_common.scss
> +}
❓별거 아니지만 위에 :root에서 한번에 관리하는게 한눈에 보기에도 찾기도 편할 것 같다고 생각이 드는데, 박하는 따로 분리해놓으신 이유가 있나요❓

2023-04-06 05:57 UTC, qkdflrgs commented on src/js/index.js
> +}
남세의 리뷰듣고 바로 피드백 하셨네요👍

2023-04-06 06:05 UTC, youzysu reviewed
코드가 넘넘 깔끔해서 보기 편했어요 박하! 저의 몇몇 생각들만 댓글로 달아두었습니다! 잘봤습니당~~

2023-04-06 06:05 UTC, youzysu commented on src/assets/img/change-btn.svg
버튼들도 그냥 svg 이미지로 하셨군요...?! 디자인이 같으니 학습 겸 SCSS 코드 작성해보셔도 좋을 것 같습니다 :)

2023-04-06 06:05 UTC, youzysu commented on src/js/modal/event.js
> +    login.addEventListener("mouseenter", function () {
function은 내부적으로 이미 구현되어 있는 내용이 많아서(무거워서) 모던 자바스크립트에서는 function 사용을 많이 안하게 된걸로 아는데요! ㅎㅎ 여기처럼 가벼운 기능의 익명함수라면 arrow function을 써보시면 어떨까요!

참고하시면 좋은 영상 아래 공유드립니다! 
> [[Javascript 미세팁] "function"은 아예 쓰지 마세요
](https://www.youtube.com/watch?v=LPEwb5plEoU&t=245s)

2023-04-06 06:05 UTC, youzysu commented on src/styles/css/style.css.map
아직도 map 파일 안지우셨다고 소문내기 전에 삭제하시죠 박하!

2023-04-06 06:05 UTC, youzysu commented on src/styles/css/style.css
(마찬가지로 scss만 수정되고 컴파일을 하지 않은 css 파일을 쓸 수 있으니까 직접 빌드해서 사용하도록 깃헙에서 관리할 필요가 없다는 이야기를 들었습니다!)

2023-04-06 06:05 UTC, youzysu commented on src/js/modal/event.js
> +        addDimming(".hero");
dimLayer를 만들지 않고, hero 영역을 아예 dim 처리해버리는걸까요? 신박하군요.

2023-04-06 06:05 UTC, youzysu commented on src/styles/scss/_nav-bar.scss
> +.hero.dim::before {
dim 클래스 추가 시 가상선택자로 dimLayer를 만들어주는거군요! 지금은 hero 영역에만 적용되는 것 같은데, main이나 body 영역에 적용하는게 더 적합할 것 같아요! dim 스타일을 공통으로 만들어두고 나중에 필요에 따라 요소에 적용해주면 되겠네요! 배워갑니다~~

2023-04-06 06:05 UTC, youzysu commented on src/js/modal/event.js
> +    const login = document.querySelector(".login");
박하도 자주 쓰이는 querySelector는 util로 만들어서 사용해보시면 어떨까요! 앞으로 요소가 많아질테니 DOM 탐색 로직도 신경써보셔도 좋을 것 같습니다 ㅎㅎ

2023-04-06 06:05 UTC, youzysu commented on src/js/modal/event.js
> +export function attachAddressEventListeners() {
(함수명에 왕도는 없지만) 개인적으로 attach는 element를 붙인다는 느낌이 드는데, add가 낫지 않을까요? 어차피 내부 함수들도 다 addEventListener인 것 같아서요

2023-04-06 06:51 UTC, bakhacode commented on src/styles/scss/_common.scss
> +}
한 번에 넣어서 되는 걸 생각못하고 있었는데 바로 합쳐줬습니다 ㅋㅋ 감사합니다!

2023-04-06 06:52 UTC, bakhacode commented on src/assets/img/change-btn.svg
구현 빨리해야지 급급하게 만들면서 다 갖다 붙였는데 다른 분들은 직접 구현하신거 보고 반성했습니다 ㅋㅋ ㅠㅠ 리태처럼 직접 구현하면 텍스트도 변경하면서 재사용 가능해서 좋은 거 같아요 구현해보겠습니다~!

2023-04-06 06:54 UTC, bakhacode commented on src/js/modal/event.js
> +    login.addEventListener("mouseenter", function () {
요 영상 지나가면서 본 적이 있던 것 같은데 이유를 하나도 기억 못하는거 보니 진짜 그냥 보기만했었나보네요 ㅋㅋㅋㅋ ㅠㅠ 조이덕에 다시 배워가요!

2023-04-06 06:55 UTC, bakhacode commented on src/styles/css/style.css.map
ㅋㅋㅋㅋㅋ 바로 싹 정리하겠습니다 🥹

2023-04-06 06:57 UTC, bakhacode commented on src/js/modal/event.js
> +        addDimming(".hero");
좋은 걸 쓰면서도 좋은지도 모르고 바꿀 생각했었는데 조이랑 리태덕에 유지하겠습니다...^^

2023-04-06 07:01 UTC, bakhacode commented on src/styles/scss/_nav-bar.scss
> +.hero.dim::before {
친절한 해석 감사합니다 🥰

2023-04-06 07:48 UTC, bakhacode commented on src/js/modal/event.js
> +    const login = document.querySelector(".login");
다른 분들은 만들어서 쓰시길래 쓰면 좋은 점이 뭐가있을까 했는데 매번 document까지 가서 찾는 건 몰랐는데 조이 설명덕에 쓰는 이유도 시원하게 알아가서 바로 적용해보려합니다 너무 감사해용 🤗

2023-04-06 07:49 UTC, bakhacode commented on src/js/modal/event.js
> +export function attachAddressEventListeners() {
attach라는 메서드가 있었꾼요..? 딱 보고 헷갈리는 느낌 아예 없게 add로 하는게 좋겠어요 !

2023-04-07 07:26 UTC, closed without merging